spring.application.name=springboot-ai-model-routingwithjev
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.api-key=${GEMINI_API_KEY}

spring.ai.openai.chat.model=models/gemini-3.6-flash
spring.ai.openai.chat.temperature=2
spring.ai.typesafe.api-key=${TYPE_SAFE_API_KEY}
